POST http://localhost:3000/api/pub
Content-Type: application/json

{ "title": "Testttt","subject":"asd", "body": 'Notified by Celala' }



###
{"publicKey":"BFZ-dGxNqg0A15IIR2-XAxn0wUKyVID9uoMuBgifai_P4eNGTNFMjS2_ly99v_WNr_4ev_5Rqb5-SU99q2Ari4o","privateKey":"XELyGjIvBX1NQPfBckaao8tRsmRzkleRvzbaWZgIGRw"}